Gorevcim.WEB/Controllers/ProductsWeightController.cs
using Microsoft.AspNetCore.Mvc;
using Gorevcim.Core.Services;
using Gorevcim.Core.DTOs;
using Gorevcim.Core;
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using Gorevcim.Core.Models;

namespace Gorevcim.WEB.Controllers
{
    public class ProductsWeightController : Controller
    {
        private readonly IProductWeightUnitsService _productWeightUnitsService;
        private readonly IMapper _mapper;

        public ProductsWeightController(IProductWeightUnitsService productWeightUnitsService, IMapper mapper)
        {
            _productWeightUnitsService = productWeightUnitsService;
            _mapper = mapper;
        } 

        public async Task<IActionResult> Index()
        {
            var productWeight = await _productWeightUnitsService.GetWebAllProductWeightUnits();
            dynamic mymodel = new ExpandoObject();
            mymodel._productWeight = productWeight;
            mymodel.activeProductWeightCount = productWeight.Where(t => t.IsActive == 1).Count();
            mymodel.passiveProductWeightCount = productWeight.Where(t => t.IsActive == 0).Count();
            return View(mymodel);
        }



        public async Task<IActionResult> Save()
        {
            var productWeight = await _productWeightUnitsService.GetAllAsync(); //    var productsColor = await _productColorsService.GetAllAsync();
            var productWeightDto = _mapper.Map<List<ProductWeightUnitsDto>>(productWeight.ToList());
            ViewBag.productWeight = new SelectList(productWeightDto, "Id", "Name");
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Save(ProductWeightUnitsDto productWeightUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productWeightUnitsService.AddAsync(_mapper.Map<ProductWeightUnits>(productWeightUnitsDto));
                TempData.Add("Success", "Ürün başarıyla eklenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Error", "Hata Oluştu. ProductsController|Save|54");
            var productWeight = await _productWeightUnitsService.GetAllAsync();
            var productWeightDto = _mapper.Map<List<ProductWeightUnitsDto>>(productWeight.ToList());
            ViewBag.productWeight = new SelectList(productWeightDto, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int Id)
        {
            var productWeight = await _productWeightUnitsService.GetByIdAsync(Id);
            var ProductWeight = await _productWeightUnitsService.GetAllAsync();
            var productWightDto = _mapper.Map<List<ProductWeightUnitsDto>>(ProductWeight.ToList());
            ViewBag.productWeight = new SelectList(productWightDto, "Id", "Name", productWeight);
            return View(_mapper.Map<ProductWeightUnitsDto>(productWeight));
        }



        [HttpPost]
        public async Task<IActionResult> Update(ProductWeightUnitsDto productWeightUnitsDto)
        {
            if (ModelState.IsValid)
            {
                await _productWeightUnitsService.UpdateAsync(_mapper.Map<ProductWeightUnits>(productWeightUnitsDto));
                TempData.Add("Info", "Ürün başarıyla güncellenmiştir.");
                return RedirectToAction(nameof(Index));
            }
            TempData.Add("Info", "Hata Oluştu. ProductsController|Update|79");
            var productWeight = await _productWeightUnitsService.GetAllAsync();
            var productWeightDto = _mapper.Map<List<ProductWeightUnitsDto>>(productWeight.ToList());
            ViewBag.productWeight = new SelectList(productWeightDto, "Id", "Name", productWeightDto);
            return View();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var productWeight = await _productWeightUnitsService.GetByIdAsync(Id);
            await _productWeightUnitsService.RemoveAsync(productWeight);
            TempData.Add("Info", "Ürün başarıyla silinmiştir.");
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int Id)
        {
            var productWeight = await _productWeightUnitsService.GetByIdAsync(Id);
            var ProductWeight = await _productWeightUnitsService.GetAllAsync();
            var productWightDto = _mapper.Map<List<ProductWeightUnitsDto>>(ProductWeight.ToList());
            ViewBag.productWeight = new SelectList(productWightDto, "Id", "Name", productWeight);
            return View(_mapper.Map<ProductWeightUnitsDto>(productWeight));
        }





    }
}

Gorevcim.WEB/Views/ProductsWeight/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model ProductWeightUnitsDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsWeight" asp-action="Details" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Ölçü Detay</h4>
                <input type="hidden" asp-for="ProductWeightId" id="ProductColorIdDetails">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label">Adı</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsNameDetails" asp-for="Name" type="text" class="form-control" disabled>

                    </div>
                </div>



                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label">Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsWebUrlDetails" asp-for="ShortCode" type="text" class="form-control" disabled>

                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label">Açıklama</label>
                    <div class="col-md-6">
                        <input id="ProductBrandsWebUrlDetails" asp-for="Explanation" type="text" class="form-control" disabled>

                    </div>
                </div>
 
            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsWeight/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model dynamic


<div class="row">
    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Aktif Ağırlık Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.activeProductWeightCount</span></h5>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-xl-2">
        <div class="card">
            <div class="card-body">
                <div>
                    <p class="text-muted mb-0">Pasif Ağırlık Birimi</p>
                    <h5 class="mb-1 mt-1"><span data-plugin="counterup">@Model.passiveProductWeightCount</span></h5>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Ağırlık Table</h4>
            <div class="table-rep-plugin">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="ProductsProjectTable" role="grid">

                        <thead>
                            <tr>
                                
                                <th>Adı</th>
                                <th>Kodu</th>
                                <th>Açıklama</th>
                                <th>Aksiyonlar</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model._productWeight)
                            {
                                <tr>
                                    
                                    <td>@item.Name</td>
                                    <td>@item.ShortCode</td>
                                    <td>@item.Explanation</td>
                             
                                    <td>
                                        <ul class="list-inline mb-0">

                                            <li class="list-inline-item">
                                                <a class="px-2 text-info" asp-controller="ProductsWeight" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="uil uil-arrow-from-right font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-primary" asp-controller="ProductsWeight" asp-action="Update" asp-route-id="@item.Id">
                                                    <i class="uil uil-pen font-size-18"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <a class="px-2 text-danger" data-bs-toggle="modal" data-bs-target="#modalDelete@(item.Id)">
                                                    <i class="uil uil-trash-alt font-size-18"></i>
                                                </a>
                                            </li>

                                        </ul>
                                    </td>
                                </tr>
                                <div class="modal fade" id="modalDelete@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="myModalLabel">Ağırlık @(item.Name) siliniyor.</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>

                                                  
                                                    Ağırlık Kodu : @(item.ShortCode) <br>

                                                    <strong>Ağırlık: @(item.Name)</strong> kalıcı olarak <strong>silinecektir.</strong>

                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-light waves-effect" data-bs-dismiss="modal">iptal</button>
                                                <a type="button" class="btn btn-primary waves-effect waves-light" asp-controller="ProductsWeight" method="post" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div>

                                <!-- /.modal -->
                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>




</div>



@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ProductsCategoryTable').DataTable(

                {
                    language: {
                        info: "_TOTAL_ kayıttan _START_ - _END_ kayıt gösteriliyor.",
                        infoEmpty: "Gösterilecek hiç kayıt yok.",
                        loadingRecords: "Kayıtlar yükleniyor.",
                        zeroRecords: "Tablo boş",

                        search: "Arama:",
                        infoFiltered: "(toplam _MAX_ kayıttan filtrelenenler)",
                        buttons: {
                            copyTitle: "Panoya kopyalandı.",
                            copySuccess: "Panoya %d satır kopyalandı",
                            copy: "Kopyala",
                            print: "Yazdır",
                        },

                        paginate: {
                            first: "İlk",
                            previous: "Önceki",
                            next: "Sonraki",
                            last: "Son"
                        },
                    },
                    dom: 'Bfrltip',
                    buttons: [
                        'copy', 'excel', 'pdf', 'print'
                    ],
                    responsive: true

                }

            );
        });
    </script>

}

Gorevcim.WEB/Views/ProductsWeight/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model ProductWeightUnitsDto




<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-action="Save" method="post" asp-controller="ProductsWeight" class="needs-validation" novalidate>
                <h4 class="card-title">Ağırlık Kayıt</h4>



                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectBrandsNameSave">Adı</label>
                    <div class="col-md-6">
                        <input asp-for="Name" type="text" class="form-control" id="ProductProjectNameSave" placeholder="Ağırlık Birimi Yazınız" required>
                        <div class="invalid-feedback"> Ağırlık Birimi Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label"> Kod</label>
                    <div class="col-md-6">
                        <input asp-for="ShortCode" id="BrandsWebUrlSave" class="form-control" type="text" placeholder="Ağırlık Birimi Kodu Yazınız" required>
                        <div class="invalid-feedback">Ağırlık Birimi Kodu Boş olamaz!</div>
                    </div>
                </div>



                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label"> Açıklama </label>
                    <div class="col-md-6">
                        <input asp-for="Explanation" id="BrandsWebUrlSave" class="form-control" type="text" placeholder="Açıklama Yazınız" required>
                        <div class="invalid-feedback">Açıklama Birimi Kodu Boş olamaz!</div>
                    </div>
                </div>

   

                <input type="submit" class="btn btn-primary waves-effect waves-light me-1 form-group" />




            </form>


        </div>
    </div>
</div>

Gorevcim.WEB/Views/ProductsWeight/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model ProductWeightUnitsDto

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <form asp-controller="ProductsWeight" asp-action="Update" method="post" class="needs-validation" novalidate>
                <h4 class="card-title">Ağırlık Birimi  Güncelle</h4>
                <input type="hidden" asp-for="ProductWeightId" id="ProductProjectIdUpdate">


                <div class="mb-3 row">
                    <label asp-for="Name" class="col-md-2 col-form-label" for="ProductProjectNameSave">Ağırlık Adı</label>
                    <div class="col-md-6">
                        <input id="ProductProjectNameUpdate" asp-for="Name" type="text" class="form-control" placeholder="Ağırlık Adı Yazınız" required>
                        <div class="invalid-feedback">Ağırlık Adı Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="ShortCode" class="col-md-2 col-form-label">Ağırlık Kodu</label>
                    <div class="col-md-6">
                        <input id="ProductProjectCodeUpdate" asp-for="ShortCode" type="text" class="form-control" placeholder="Ağırlık Kısa Kodunu Yazınız" required>
                        <div class="invalid-feedback">Ağırlık Kısa Kodu Boş olamaz!</div>
                    </div>
                </div>


                <div class="mb-3 row">
                    <label asp-for="Explanation" class="col-md-2 col-form-label">Açıklama</label>
                    <div class="col-md-6">
                        <input id="ProductProjectCodeUpdate" asp-for="Explanation" type="text" class="form-control" placeholder="Açıklama Yazınız" required>
                        <div class="invalid-feedback">Açıklama Boş olamaz!</div>
                    </div>
                </div>


                <input type="submit" value="Güncelle" class="btn btn-primary waves-effect waves-light me-1 form-group" />











            </form>


        </div>
    </div>
</div>